apiVersion: v1
kind: Service
metadata:
  name: {{ include "kanban.serverServiceName" . }}
  labels:
    {{- include "kanban.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "kanban.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP

